// EXCERPT — the shape of one step, to adapt. The real file is
// `lib/core/db/migrations.dart`: the ONE hand-written file under `lib/core/db/`
// (CONVENTIONS.md §1). Do not copy this file into the tree.

import 'package:drift/drift.dart';

// Generated by `drift_dev schema steps`. Never hand-edited. It supplies
// `stepByStep`, `Schema2`, `Schema3`, … — the HISTORICAL schemas.
import 'schema_versions.dart';

/// Wired in `lib/core/db/database.dart` as `onUpgrade: shedUpgrade`.
/// One entry per hop, in order, forever. Editing a released entry splits the
/// fleet into two schemas with the same version number (04 §2.9).
final OnUpgrade shedUpgrade = stepByStep(
  from1To2: _from1To2,
);

/// v2 adds `ewes.eid` — the EID transponder number. Nullable, no default:
/// a default here would be the app answering for the shepherd (spec §12.1).
///
/// `schema` is the schema **as it exists at v2**, not today's. Every reference
/// below goes through it. Writing `db.ewes`, or importing the table class from
/// `database.dart`, makes this step break on the day v9 adds a column —
/// `check_policy` rule `db.migration_today_schema` (CONVENTIONS R54).
Future<void> _from1To2(Migrator m, Schema2 schema) async {
  // Additive vocabulary, and nothing else: createTable / addColumn /
  // createIndex (04 §2.1 rule 2).
  await m.addColumn(schema.ewes, schema.ewes.eid);

  // SQLite creates no index for you, and the EID lookup only ever asks about
  // animals that still exist — so the index is partial, matching the tag
  // indexes in 03 §6.
  //
  // Prefer `await m.createIndex(schema.<name>);` if the generated `Schema2`
  // exposes the index — READ `lib/core/db/schema_versions.dart` and check
  // before you choose. `issueCustomQuery` is the fallback, and it is legal
  // only because this file is inside `lib/core/db/`.
  //
  // The index name follows CONVENTIONS §4.6: `idx_<table-abbrev>_<columns>`,
  // matching 03's `idx_ewe_tag_active` / `idx_ewe_tagdigits`. An index name is
  // in the committed schema snapshot, so getting it wrong is a migration to
  // fix it, not a rename.
  await m.issueCustomQuery(
    "CREATE INDEX IF NOT EXISTS idx_ewe_eid ON ewes (eid) "
    "WHERE eid IS NOT NULL;",
  );

  // A backfill may write STRUCTURAL values only — 0, NULL, '', a value copied
  // from another column, `newUid()`, `appNow()`. This one copies; it invents
  // nothing:
  //
  //   await m.issueCustomQuery(
  //     'UPDATE ewes SET eid = NULL WHERE eid = \'\';',
  //   );
  //
  // NEVER a domain value. This is what a §12.1 violation looks like as a
  // migration, and no gate catches it:
  //
  //   UPDATE treatment_withdrawals SET target = COALESCE(target, 'meat');
  //   UPDATE lambings SET declared_birth_type = 1 WHERE declared_birth_type IS NULL;
  //
  // (`declared_birth_type` stores `BirthType.code`, an INTEGER 1..5 — CONVENTIONS
  // §2.9, R6 — and it is nullable precisely so "no strokes tallied yet" is a
  // storable fact. There is no birth-type chooser in the product; the type is
  // derived from the tally strokes, so a backfill here invents a litter size
  // nobody tapped.)
  //
  // A treatment with no withdrawal row reads as `WithdrawalNotRecorded`, and
  // that is the correct answer (decisions #51/#52). Absent data is a fact.

  // NEVER SQL-side time (#47). `CURRENT_TIMESTAMP`, `date('now')` and
  // `datetime('now')` are banned here as everywhere; an instant comes from
  // `appNow()` in Dart and is passed in as a bound argument.

  // If this step had rebuilt a table — a CHECK change, a new NOT NULL, an FK
  // change — it would be `await m.alterTable(TableMigration(schema.ewes));`
  // with no columnTransformer, plus `PRAGMA defer_foreign_keys = ON` inside
  // the transaction and a closing `PRAGMA foreign_key_check`, because
  // `PRAGMA foreign_keys` is a no-op inside drift's migration transaction.
  // A rebuild also obliges a data-integrity test for this hop (04 §2.6, #38).
}
