// test/policy/gate_rules_test.dart — the one file every rule in tool/check_policy.dart
// is proved in. 00-README §9 step 1: a rule nobody has seen fire is
// indistinguishable from a broken rule, so a row and the case that watches it
// fire land in the same commit — always.
//
// Every planted violation lives in a **temp tree**, never as a literal in this
// file. `test/` is a scanned root, so a banned literal written here would trip
// the gate on the gate's own proving test.
@Tags(<String>['policy'])
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

// ignore: always_use_package_imports
import '../../tool/check_policy.dart';

/// The smallest allowlist the gate will accept: four sections, no entries.
const String _emptyAllowlist = '''
[dependencies]
[dev_dependencies]
[transitive]
[exempt]
''';

/// A lockfile with no packages in it, so a case that is not about G2 does not
/// have to think about G2. Cases that *are* about G2 pass their own.
const String _emptyLockfile = '''
# Generated by pub
packages:
sdks:
  dart: ">=3.12.0 <4.0.0"
''';

/// Writes [files] into a throwaway tree, runs the gate over it, returns the
/// violations. The planted text lives in the temp tree, never in this file.
List<String> gateOn(
  Map<String, String> files, {
  String allowlist = _emptyAllowlist,
  String lockfile = _emptyLockfile,
}) {
  final Directory temp = _tree(files, allowlist: allowlist, lockfile: lockfile);
  try {
    return runPolicy(root: temp.path);
  } finally {
    temp.deleteSync(recursive: true);
  }
}

/// The same tree, handed back unrun — for the cases that read the allowlist
/// directly or assert on the walk.
Directory _tree(Map<String, String> files, {String? allowlist, String? lockfile}) {
  final Directory temp = Directory.systemTemp.createTempSync('shed_gate_');
  if (allowlist != null) {
    _write(temp, 'tool/policy_allowlist.txt', allowlist);
  }
  if (lockfile != null) {
    _write(temp, 'pubspec.lock', lockfile);
  }
  files.forEach((String path, String content) => _write(temp, path, content));
  return temp;
}

void _write(Directory root, String path, String content) {
  final File file = File('${root.path}/$path');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(content);
}

/// A literal a later rule will ban, assembled from halves so this file never
/// contains it whole. `time.dart_clock` bans it under `lib/` from N03-T06.
final String _willBeBanned =
    'DateTime'
    '.now()';

/// One planted violation: where it goes, what it says, and — for the three
/// `dep.*` ids — the synthetic lockfile that produces it instead.
typedef Planted = ({String path, String source, String? lockfile, Map<String, String>? extra});

Planted _at(String path, String source) =>
    (path: path, source: source, lockfile: null, extra: null);

/// A planting that needs MORE THAN ONE FILE.
///
/// `launch.colour_parity` compares two files in two languages, so a
/// single-file planting cannot trip it. Everything else stays one file, which
/// is why this is a second constructor rather than a widened first.
Planted _atAll(String path, String source, Map<String, String> extra) =>
    (path: path, source: source, lockfile: null, extra: extra);

Planted _lock(String name, String kind) => (
  extra: null,
  path: 'lib/keep.dart',
  source: 'void main() {}\n',
  lockfile:
      '# Generated by pub\npackages:\n  $name:\n    dependency: "$kind"\n'
      '    source: hosted\n    version: "1.0.0"\nsdks:\n  dart: ">=3.12.0 <4.0.0"\n',
);

/// Rule id → the smallest planting that must trip it.
///
/// **This map is the proof.** A row with no entry fails the inventory assertion
/// from one side; an entry with no row fails it from the other, which is what
/// catches a rule removed in a tidy-up while the suite stays green.
///
/// Every snippet for a row scoped to BOTH roots is assembled from adjacent
/// string literals, so this file — which lives under a scanned root — never
/// holds the needle whole. That is one of the two ways out the epic names; the
/// other would be a fifth `[exempt]` line, and there is no fifth `[exempt]` line.
final Map<String, Planted> firesOn = <String, Planted>{
  // -- launch (06 §9.4) ------------------------------------------------------
  // THE ONE RULE THAT READS OUTSIDE lib/, and the only planting that needs two
  // files: it compares a Dart const with an Android colour resource, so one file
  // cannot disagree with anything. #0A0A0B against #0B0D0E is the exact pair
  // P14 was about — a one-digit difference nobody sees until a cold launch on a
  // real phone.
  'launch.colour_parity': _atAll(
    'lib/core/ui/primitives.dart',
    'const Color nSurface04 = Color(0xFF0A0A0B);',
    <String, String>{
      'android/app/src/main/res/values/colors.xml':
          '<resources><color name="shed_surface_base">#FF0B0D0E</color></resources>',
    },
  ),

  // -- layer (CONVENTIONS §1.1) ---------------------------------------------
  'layer.domain': _at(
    'lib/domain/withdrawal/clear_date.dart',
    "import 'package:clock/clock.dart';",
  ),
  'layer.core_db': _at(
    'lib/core/db/database.dart',
    "import 'package:shed_book/core/ui/tokens.dart';",
  ),
  'layer.data': _at('lib/data/flock_repository.dart', "import '../features/flock/screen.dart';"),
  'layer.data_no_material': _at(
    'lib/data/lambing_repository.dart',
    "import 'package:flutter/material.dart';",
  ),
  'layer.features': _at(
    'lib/features/flock/flock_screen.dart',
    "import 'package:drift/drift.dart';",
  ),
  'layer.sibling': _at(
    'lib/features/lambing/foster_screen.dart',
    "import '../flock/ewe_card_screen.dart';",
  ),
  'layer.core_ui': _at(
    'lib/core/ui/components/shed_pen_tile.dart',
    "import 'package:shed_book/data/models.dart';",
  ),
  'layer.single_writer': _at(
    'lib/features/pens/pen_board_screen.dart',
    "import 'package:sqlite3/sqlite3.dart';",
  ),
  'layer.root': _at('lib/main.dart', "import 'package:shed_book/core/db/database.dart';"),
  'layer.data_no_validation': _at(
    'lib/data/lambing_repository.dart',
    "import 'package:shed_book/domain/validation/warning.dart';",
  ),
  'layer.import': _at('lib/data/export_repository.dart', "import 'package:http/http.dart';"),

  // -- net (G3) --------------------------------------------------------------
  'net.http_client': _at('lib/data/share_service.dart', 'void f() { final c = HttpClient(); }'),
  'net.socket': _at('lib/core/log/local_log.dart', 'void f() { Socket.connect(h, p); }'),
  'net.web_socket': _at(
    'lib/data/notification_scheduler.dart',
    "void f() { WebSocket.userAgent = 'x'; }",
  ),
  'net.image_network': _at(
    'lib/core/ui/components/shed_photo.dart',
    'Widget b() => Image.network(u);',
  ),
  'net.pdf_fonts': _at(
    'lib/features/export/pdf_builder.dart',
    'final f = PdfGoogleFonts.helvetica();',
  ),
  'net.sync_timer': _at('lib/core/time/ticker.dart', 'void f() { Timer.periodic(d, cb); }'),

  // -- time ------------------------------------------------------------------
  'time.dart_clock': _at(
    'lib/data/lambing_repository.dart',
    'final t = DateTime'
        '.now();',
  ),
  'time.sql_now_1': _at('lib/core/db/queries.dart', 'const q = "date(\'now\')";'),
  'time.sql_now_2': _at('lib/core/db/queries.dart', 'const q = "datetime(\'now\')";'),
  'time.sql_now_3': _at('lib/core/db/queries.dart', "const q = 'CURRENT_TIMESTAMP';"),
  'time.sql_now_4': _at('lib/core/db/queries.dart', "const q = 'CURRENT_DATE';"),
  'time.sql_now_5': _at('lib/core/db/queries.dart', "const q = 'CURRENT_TIME';"),

  // -- the single writer's text half, streams and statistics -----------------
  'db.raw_statement': _at('lib/data/pen_repository.dart', 'void f() => customStatement(sql);'),
  'db.save_verb': _at('lib/data/flock_repository.dart', 'Future<void> saveEwe(Ewe e) async {}'),
  // **THE ONE RULE HERE THAT GUARDS SOMEBODY'S MONEY.** An entitlement is never
  // revoked (`11 §12.2`): a shed has no signal most of the time the store is
  // asked, so *"the store did not confirm"* is the normal case, and an app that
  // downgraded on it would take the unlock away from a shepherd in a barn at
  // 03:20 for a network they never had.
  // **THE `firesOn` ENTRY AS WELL AS THE DESIGN GROUP'S.** The two inventories
  // ask different questions — *does this design row have a planting* and *has
  // every rule in the table been seen to fire* — and a rule proved in one but
  // not the other is a rule nobody has watched fail.
  // **A CURRENCY SYMBOL FOLLOWED BY A DIGIT, ANYWHERE UNDER `lib/`.** The price
  // arrives from the store already localised and currency-formatted for the
  // account that will be charged; a literal is wrong for most of the world the
  // day it ships, and a `NumberFormat.currency` call is wrong more subtly — it
  // formats the number correctly in the wrong currency.
  'copy.currency_literal': _at(
    'lib/features/settings/settings_screen.dart',
    "const p = 'Unlock for £24.99';",
  ),
  'ui.monetization_surface': _at(
    'lib/features/quick_entry/quick_entry_screen.dart',
    'final u = ref.watch(entitlementProvider);',
  ),
  'db.entitlement_revoke': _at(
    'lib/data/entitlement_repository.dart',
    'final c = EntitlementsCompanion(unlocked: const Value<bool>(false));',
  ),
  'stream.combine': _at('lib/data/season_repository.dart', 'final s = combineLatest(a, b);'),
  'stream.invalidate': _at(
    'lib/features/season/season_controller.dart',
    'void f() => ref.invalidate(p);',
  ),
  'stat.zero_default': _at('lib/features/season/season_controller.dart', 'final n = count ?? 0;'),
  'stat.zero_default2': _at('lib/features/flock/flock_controller.dart', 'final n = count ?? 0;'),

  // -- rp3 (13 §2.5 fixes the count at thirteen) -----------------------------
  'rp3.retry': _at(
    'lib/app.dart',
    'ProviderScope(re'
        'try: r);',
  ),
  'rp3.container_test': _at(
    'lib/app.dart',
    'final c = ProviderContainer'
        '.test();',
  ),
  'rp3.tester_container': _at(
    'test/features/flock_screen_test.dart',
    'final c = tester'
        '.container;',
  ),
  'rp3.is_auto_dispose': _at(
    'lib/app.dart',
    'final b = p.is'
        'AutoDispose;',
  ),
  'rp3.mutation': _at(
    'lib/app.dart',
    'final m = Muta'
        'tion<int>();',
  ),
  'rp3.value_or_null': _at(
    'lib/app.dart',
    'final v = a.value'
        'OrNull;',
  ),
  'rp3.ref_mounted': _at(
    'lib/app.dart',
    'if (ref.mou'
        'nted) {}',
  ),
  'rp3.observer_context': _at(
    'lib/app.dart',
    'void f(ProviderObserver'
        'Context c) {}',
  ),
  'rp3.state_provider': _at(
    'lib/app.dart',
    'final p = State'
        'Provider((r) => 0);',
  ),
  'rp3.state_notifier': _at(
    'lib/app.dart',
    'class C extends State'
        'Notifier<int> {}',
  ),
  'rp3.annotation': _at(
    'lib/app.dart',
    "import 'package:riverpod"
        "_annotation/x.dart';",
  ),
  'rp3.hooks': _at(
    'lib/app.dart',
    "import 'package:hooks"
        "_riverpod/x.dart';",
  ),
  'rp3.overrides': _at('lib/app.dart', 'final o = p.overrideWith((r) => fake);'),

  // -- tokens, themes, typography (06 §3.5) ----------------------------------
  'token.raw_color': _at(
    'lib/features/lambing/lambing_screen.dart',
    'const c = Color(0xFF0B0D0E);',
  ),
  'token.material_color': _at(
    'lib/features/lambing/lambing_screen.dart',
    'const c = Colors.transparent;',
  ),
  'token.raw_color_ctor': _at(
    'lib/features/lambing/lambing_screen.dart',
    'const c = Color.fromARGB(255, 1, 2, 3);',
  ),
  'token.seeded_scheme': _at(
    'lib/core/ui/theme.dart',
    'final s = ColorScheme.fromSeed(seedColor: c);',
  ),
  'token.literal_font_size': _at(
    'lib/features/lambing/lambing_screen.dart',
    'const t = TextStyle(fontSize: 20);',
  ),
  'token.color_scheme_read': _at(
    'lib/features/flock/flock_screen.dart',
    'final c = Theme.of(context).colorScheme;',
  ),
  'token.color_scheme_read_ui': _at(
    'lib/core/ui/components/shed_pen_tile.dart',
    'final c = Theme.of(context).colorScheme;',
  ),
  'token.primitives_import': _at(
    'lib/features/lambing/lambing_screen.dart',
    "import 'package:shed_book/core/ui/primitives.dart';",
  ),
  'token.magic_size': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => SizedBox(height: 12);',
  ),
  'theme.mode': _at('lib/app.dart', 'final m = ThemeMode.system;'),
  'theme.brightness': _at('lib/app.dart', 'final b = Brightness.light;'),
  'theme.platform_brightness': _at(
    'lib/app.dart',
    'final b = MediaQuery.platformBrightnessOf(context);',
  ),
  'theme.light_factory': _at('lib/app.dart', 'final s = ColorScheme.light();'),
  'theme.deprecated_scheme_role': _at(
    'lib/core/ui/theme.dart',
    'const s = ColorScheme(background: c);',
  ),
  'type.google_fonts': _at('lib/core/ui/typography.dart', 'final f = GoogleFonts.inter();'),
  'type.clamp': _at('lib/app.dart', 'Widget b() => MediaQuery.withClampedTextScaling(child: c);'),
  'type.weight_cap': _at('lib/core/ui/typography.dart', 'const w = FontWeight.w800;'),
  'type.fitted_box': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => FittedBox(child: c);',
  ),

  // -- gestures (06 §7) ------------------------------------------------------
  'gesture.dismissible': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => Dismissible(key: k, child: c);',
  ),
  'gesture.draggable': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => Draggable(child: c, feedback: f);',
  ),
  'gesture.tooltip': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => Tooltip(message: m, child: c);',
  ),
  'gesture.long_press_draggable': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => LongPressDraggable(child: c, feedback: f);',
  ),
  'gesture.interactive_viewer': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => InteractiveViewer(child: c);',
  ),
  'gesture.refresh': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => RefreshIndicator(child: c, onRefresh: r);',
  ),
  'gesture.long_press': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => GestureDetector(onLongPress: f);',
  ),
  'gesture.scale': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => GestureDetector(onScaleStart: f);',
  ),
  'gesture.drag': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => GestureDetector(onHorizontalDragStart: f);',
  ),
  'gesture.drag_handle': _at(
    'lib/core/ui/components/shed_bottom_sheet.dart',
    'void f() => s(showDragHandle: true);',
  ),
  'gesture.sheet_drag': _at(
    'lib/core/ui/components/shed_bottom_sheet.dart',
    'void f() => s(enableDrag: true);',
  ),
  'gesture.slider': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => Slider(value: v, onChanged: c);',
  ),
  'gesture.horizontal_swipe': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => PageView(children: c);',
  ),
  'gesture.raw_snackbar': _at('lib/core/ui/feedback.dart', 'void f() { m.showSnackBar(s); }'),

  // -- semantics and the two CONVENTIONS §4.7 additions ----------------------
  'a11y.scale_factor': _at(
    'lib/features/lambing/lambing_screen.dart',
    'final s = MediaQuery.of(context).textScaleFactor;',
  ),
  'a11y.header_bool': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => Semantics(header: true, child: c);',
  ),
  'a11y.announce': _at(
    'lib/features/lambing/lambing_screen.dart',
    'void f() => SemanticsService.announce(m, d);',
  ),
  'a11y.sort_key': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => Semantics(sortKey: const OrdinalSortKey(1), child: c);',
  ),
  'a11y.merge_semantics': _at(
    'lib/features/lambing/lambing_screen.dart',
    'Widget b() => MergeSemantics(child: c);',
  ),
  'a11y.material_picker': _at(
    'lib/features/treatments/treatments_screen.dart',
    'void f() => showDatePicker(context: c);',
  ),
  'ui.spinner': _at(
    'lib/features/flock/flock_screen.dart',
    'Widget b() => CircularProgressIndicator();',
  ),
  'ui.show_dialog': _at(
    'lib/features/settings/settings_screen.dart',
    'void f() => showDialog(context: c, builder: b);',
  ),

  // -- vocabulary (CONVENTIONS §5) -------------------------------------------
  'copy.banned_word': _at(
    'lib/features/lambing/lambing_screen.dart',
    'const s = '
        "'dr"
        "aft';",
  ),
  'type.error_name': _at(
    'lib/domain/validation/failures.dart',
    'class LambingError implements Exception {}',
  ),
  // The two copy rules land with N06-T09. Both entries plant into a DART STRING
  // LITERAL, because that is the scope 05 §7.3 fixes and the scope the driver
  // reads: comments are stripped before literals are extracted.
  'copy.vet_advice': _at(
    'lib/features/lambing/entry.dart',
    "const String hint = 'You should give 2 ml/kg of colostrum.';",
  ),
  'copy.disclaimer_retyped': _at(
    'lib/features/export/pdf.dart',
    "const String footer = 'It is not a statutory medicine record.';",
  ),
  'copy.tier3_claim': _at(
    'lib/features/settings/about_screen.dart',
    "const s = 'your data never leaves "
        "your phone';",
  ),

  // -- restore, N22-T05 ----------------------------------------------------
  'layer.plugin_file_selector': _at(
    'lib/features/export/export_screen.dart',
    "import 'package:file_selector/file_selector.dart';",
  ),

  // -- share, N21-T06 ------------------------------------------------------
  'layer.plugin_share_plus': _at(
    'lib/features/export/export_screen.dart',
    "import 'package:share_plus/share_plus.dart';",
  ),
  'export.share_static': _at(
    'lib/features/export/export_screen.dart',
    'await Share.shareXFiles(files);',
  ),
  'share.from_data': _at('lib/data/backup_format.dart', 'final f = XFile.fromData(bytes);'),

  // -- export, N21-T01. The two CONFINEMENT rows, whose shape is neither
  // "banned everywhere" nor "banned under a prefix": a pattern legal in one
  // named file and nowhere else, and its inverse.
  //
  // `export.csv_bytes` plants under lib/ but NOT in csv_writer.dart, because
  // that file is the definition rather than an exemption — planting there would
  // prove the opposite of the rule.
  'export.csv_bytes': _at('lib/features/export/share_sheet.dart', "const String eol = '\\r\\n';"),
  // The inverse: this one plants INSIDE the confined file, because the rule is
  // "not here", and layer rule 3 permits package:intl everywhere else in
  // lib/data/.
  'export.intl_in_writer': _at('lib/data/csv_writer.dart', "import 'package:intl/intl.dart';"),

  // -- G2, which fires off the lockfile and not off a source file ------------
  'dep.direct_main': _lock('connectivity_plus', 'direct main'),
  'dep.direct_dev': _lock('connectivity_plus', 'direct dev'),
  'dep.transitive': _lock('connectivity_plus', 'transitive'),
};

void main() {
  test('check_policy exits 0 on a clean tree and skips every generated file', () {
    // One ordinary file, plus one of each of 00-README §7.3's four generated
    // shapes — three of which are not *.g.dart and are not skipped by the
    // driver as 01 §3.2 prints it. Every generated one carries a literal a
    // later rule bans.
    final List<String> violations = gateOn(<String, String>{
      'lib/main.dart': 'void main() {}\n',
      'lib/core/db/database.g.dart': 'final x = $_willBeBanned;\n',
      'lib/core/db/search.drift.dart': 'final x = $_willBeBanned;\n',
      'lib/l10n/app_localizations_en.dart': 'final x = $_willBeBanned;\n',
      'test/drift/generated/schema_v1.dart': 'final x = $_willBeBanned;\n',
    });
    expect(violations, isEmpty);
  });

  test('a missing allowlist file is exit 2, not exit 0', () {
    final Directory temp = _tree(<String, String>{'lib/main.dart': 'void main() {}\n'});
    addTearDown(() => temp.deleteSync(recursive: true));
    expect(
      () => runPolicy(root: temp.path),
      throwsA(
        isA<PolicyConfigProblem>().having(
          (PolicyConfigProblem p) => p.message,
          'message',
          contains('tool/policy_allowlist.txt'),
        ),
      ),
      reason: 'a gate that cannot read its own configuration has failed to run, not passed',
    );
  });

  test('an allowlist line outside any section is refused with its line number', () {
    expect(
      () => gateOn(const <String, String>{}, allowlist: 'drift\n[dependencies]\n'),
      throwsA(
        isA<PolicyConfigProblem>().having(
          (PolicyConfigProblem p) => p.message,
          'message',
          allOf(contains('line 1'), contains('drift')),
        ),
      ),
      reason: "01 §3.2's parser swallows this line with a null-aware call on an absent map entry",
    );
  });

  test('an unknown section header is refused', () {
    expect(
      () => gateOn(const <String, String>{}, allowlist: '[deps]\ndrift\n'),
      throwsA(
        isA<PolicyConfigProblem>().having(
          (PolicyConfigProblem p) => p.message,
          'message',
          allOf(contains('line 1'), contains('deps')),
        ),
      ),
      reason: '[deps] for [dependencies] would empty an entire allowlist section silently',
    );
  });

  test('a header with text appended to it is refused, not read as an entry', () {
    // `[exempt] line with` opens like a header and does not close like one, so
    // the parser would otherwise add it as an ENTRY under whatever section came
    // before. Found by exactly that accident in this project's own allowlist.
    expect(
      () => gateOn(const <String, String>{}, allowlist: '[dependencies]\n[exempt] line with\n'),
      throwsA(
        isA<PolicyConfigProblem>().having(
          (PolicyConfigProblem p) => p.message,
          'message',
          allOf(contains('line 2'), contains('does not close it')),
        ),
      ),
    );
  });

  test('an exempt line with no :: separator is refused', () {
    expect(
      () => gateOn(
        const <String, String>{},
        allowlist: '$_emptyAllowlist lib/core/time/app_clock.dart time.dart_clock\n',
      ),
      throwsA(
        isA<PolicyConfigProblem>().having(
          (PolicyConfigProblem p) => p.message,
          'message',
          contains('::'),
        ),
      ),
    );
  });

  test('a column-aligned exempt line matches the driver lookup key', () {
    final Directory temp = _tree(
      const <String, String>{},
      allowlist:
          '$_emptyAllowlist'
          'lib/core/time/app_clock.dart       ::   time.dart_clock\n',
    );
    addTearDown(() => temp.deleteSync(recursive: true));
    expect(
      readAllowlist(temp.path)['exempt'],
      contains('lib/core/time/app_clock.dart :: time.dart_clock'),
      reason:
          '01 §3.2 prints the file padded for readability and looks it up unpadded; '
          'storing the raw line makes every exemption ever written silently inert',
    );
  });

  test('comments and blank lines are ignored, and # ends a line', () {
    final Directory temp = _tree(
      const <String, String>{},
      allowlist: '''
# a whole-line comment
[dependencies]

drift            # the only generator
[dev_dependencies]
[transitive]
http             # via timezone AND via package_info_plus. Two regular edges.
[exempt]
''',
    );
    addTearDown(() => temp.deleteSync(recursive: true));
    final Map<String, Set<String>> allow = readAllowlist(temp.path);
    expect(allow['dependencies'], equals(<String>{'drift'}));
    expect(allow['transitive'], equals(<String>{'http'}));
    expect(allow['dev_dependencies'], isEmpty);
  });

  test('the walk is not affected by filesystem order', () {
    // Two trees holding the same files, created in opposite order. The gate
    // sorts before it reports, so the answer must not depend on the order the
    // filesystem hands them back — which differs between macOS and the runner.
    const List<String> paths = <String>[
      'lib/zebra.dart',
      'lib/core/alpha.dart',
      'test/policy/mid.dart',
    ];
    List<String> walk(Iterable<String> order) {
      final Directory temp = _tree(<String, String>{
        for (final String p in order) p: 'void main() {}\n',
      }, allowlist: _emptyAllowlist);
      addTearDown(() => temp.deleteSync(recursive: true));
      return scannedFiles(temp.path);
    }

    expect(walk(paths), equals(walk(paths.reversed)));
    expect(walk(paths), orderedEquals(<String>[...paths]..sort()));
  });

  group('the layer rules — CONVENTIONS §1.1', () {
    /// One planted file, one expected rule id, exactly one message.
    void plants(String title, {required String path, required String source, required String id}) {
      test(title, () {
        final List<String> violations = gateOn(<String, String>{path: source});
        expect(violations, hasLength(1), reason: violations.join('\n'));
        expect(violations.single, contains('[$id]'));
        expect(violations.single, contains(path));
      });
    }

    void allows(String title, Map<String, String> files) {
      test(title, () => expect(gateOn(files), isEmpty));
    }

    plants(
      'layer.domain — the domain takes now as a parameter, never package:clock',
      path: 'lib/domain/withdrawal/clear_date.dart',
      source: "import 'package:clock/clock.dart';\n",
      id: 'layer.domain',
    );

    plants(
      'layer.core_db — R16 reaches lib/core/, not lib/core/ui/',
      path: 'lib/core/db/database.dart',
      source: "import 'package:shed_book/core/ui/tokens.dart';\n",
      id: 'layer.core_db',
    );

    plants(
      'layer.data — a repository may not name a screen',
      path: 'lib/data/flock_repository.dart',
      source: "import '../features/flock/flock_screen.dart';\n",
      id: 'layer.data',
    );

    plants(
      'layer.data_no_material — the data tier has no widgets',
      path: 'lib/data/lambing_repository.dart',
      source: "import 'package:flutter/material.dart';\n",
      id: 'layer.data_no_material',
    );

    // The anchor. The task title says layer.features_no_db; the id is
    // CONVENTIONS §1.1's, which outranks a task title on any name.
    plants(
      'layer.features_no_db exits 1 on a planted drift import under lib/features/',
      path: 'lib/features/flock/flock_screen.dart',
      source: "import 'package:drift/drift.dart';\n",
      id: 'layer.features',
    );

    plants(
      'layer.sibling — one feature may not name another',
      path: 'lib/features/lambing/foster_screen.dart',
      source: "import '../flock/ewe_card_screen.dart';\n",
      id: 'layer.sibling',
    );

    test('layer.sibling names both features and the remedy', () {
      final List<String> violations = gateOn(<String, String>{
        'lib/features/lambing/foster_screen.dart': "import '../flock/ewe_card_screen.dart';\n",
      });
      expect(
        violations.single,
        allOf(contains('"lambing"'), contains('"flock"'), contains('lib/data/')),
      );
    });

    plants(
      'layer.core_ui — a shared widget may not reach the data tier',
      path: 'lib/core/ui/components/shed_pen_tile.dart',
      source: "import 'package:shed_book/data/models.dart';\n",
      id: 'layer.core_ui',
    );

    plants(
      'layer.single_writer — package:sqlite3 outside lib/data/ and lib/core/db/',
      path: 'lib/features/pens/pen_board_screen.dart',
      source: "import 'package:sqlite3/sqlite3.dart';\n",
      id: 'layer.single_writer',
    );

    plants(
      'layer.root — main.dart may not reach the database',
      path: 'lib/main.dart',
      source: "import 'package:shed_book/core/db/database.dart';\n",
      id: 'layer.root',
    );

    plants(
      'layer.data_no_validation — spec §12.4 structural half',
      path: 'lib/data/lambing_repository.dart',
      source: "import 'package:shed_book/domain/validation/warning.dart';\n",
      id: 'layer.data_no_validation',
    );

    allows('a legal domain import is legal', <String, String>{
      'lib/domain/stats/losses.dart':
          "import 'package:collection/collection.dart';\nimport 'dart:math';\n",
    });

    allows('data may reach the rest of the domain — only validation is closed', <String, String>{
      'lib/data/treatment_repository.dart':
          "import 'package:shed_book/domain/withdrawal/clear_date.dart';\n",
    });

    allows('routing may name a feature', <String, String>{
      'lib/routing/routes.dart': "import '../features/flock/flock_screen.dart';\n",
    });

    allows('a feature may name itself', <String, String>{
      'lib/features/flock/flock_screen.dart': "import 'widgets/ewe_row.dart';\n",
    });

    allows(
      'no direction rule outside lib/ — the test tier may reach the database',
      <String, String>{
        'test/support/harness.dart': "import 'package:shed_book/core/db/database.dart';\n",
      },
    );

    plants(
      'export counts exactly as import does',
      path: 'lib/data/models.dart',
      source: "export '../features/flock/flock_screen.dart';\n",
      id: 'layer.data',
    );

    test('the package: and relative spellings of one violation agree', () {
      final List<String> viaPackage = gateOn(<String, String>{
        'lib/data/flock_repository.dart':
            "import 'package:shed_book/features/flock/screen.dart';\n",
      });
      final List<String> viaRelative = gateOn(<String, String>{
        'lib/data/flock_repository.dart': "import '../features/flock/screen.dart';\n",
      });
      expect(viaPackage, hasLength(1));
      expect(viaRelative, hasLength(1));
      expect(viaPackage.single.split(']').first, viaRelative.single.split(']').first);
    });

    test('more .. than depth escapes lib/, resolves to no layer and is skipped', () {
      // Recorded rather than guarded: the analyzer rejects such an import
      // anyway, and clamping would hide the fact that it resolves nowhere.
      expect(
        gateOn(<String, String>{
          'lib/data/flock_repository.dart': "import '../../../../elsewhere/thing.dart';\n",
        }),
        isEmpty,
      );
    });

    test('_layers order is the rule — core/db resolves to core/db, not core/', () {
      // If the list were sorted alphabetically, lib/core/db/ would resolve to
      // lib/core/, which IS allowed to import lib/core/ui/, and R16 would
      // disappear with no test failing. This is that test.
      expect(
        gateOn(<String, String>{
          'lib/core/db/database.dart': "import 'package:shed_book/core/ui/tokens.dart';\n",
        }).single,
        contains('[layer.core_db]'),
      );
    });
  });

  group('the net.* rules — G3, the import scan', () {
    /// The twelve `_bannedEverywhere` prefixes, spelled here so a deletion from
    /// the set is a failing case and not a quietly smaller gate. Two carry no
    /// trailing slash on purpose: they are prefixes over a family.
    const List<String> bannedPackageUris = <String>[
      'package:http/http.dart',
      'package:dio/dio.dart',
      'package:connectivity_plus/connectivity_plus.dart',
      'package:workmanager/workmanager.dart',
      'package:battery_plus/battery_plus.dart',
      'package:web_socket_channel/web_socket_channel.dart',
      'package:firebase_core/firebase_core.dart',
      'package:google_fonts/google_fonts.dart',
      'package:printing/printing.dart',
      'package:speech_to_text/speech_to_text.dart',
      'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart',
      'package:permission_handler/permission_handler.dart',
    ];

    test('net.http_import exits 1 on a planted package:http import, '
        'and no rule scans pubspec.lock for http', () {
      // Half one: the import is caught.
      final List<String> violations = gateOn(<String, String>{
        'lib/data/export_repository.dart': "import 'package:http/http.dart';\n",
      });
      expect(violations, hasLength(1), reason: violations.join('\n'));
      expect(violations.single, contains('lib/data/export_repository.dart'));
      expect(violations.single, contains('[layer.import]'));

      // Half two, and it is the half that matters in three years. `http 1.6.0`
      // sits on two regular edges, so a lockfile rule for it is permanently
      // red and gets deleted by whoever meets it — leaving no gate at all.
      expect(
        policyRuleIds.where((String id) => id.startsWith('net.')),
        isNotEmpty,
        reason: 'G3 claims our source cannot reach a network API; no net.* row proves nothing',
      );
      for (final (String id, String under) in policyRuleScopes) {
        expect(
          under,
          isNot(contains('pubspec.lock')),
          reason:
              'rule $id reads the lockfile. A "no http in pubspec.lock" rule is '
              'UNSATISFIABLE — four research notes wrote it. G2 makes the narrower '
              'true claim: no package enters the graph unreviewed',
        );
      }
    });

    void plantsText(
      String title, {
      required String path,
      required String body,
      required String id,
    }) {
      test(title, () {
        final List<String> violations = gateOn(<String, String>{path: body});
        expect(violations, hasLength(1), reason: violations.join('\n'));
        expect(violations.single, contains('[$id]'));
      });
    }

    plantsText(
      'net.http_client',
      path: 'lib/data/share_service.dart',
      body: 'void f() { final c = HttpClient(); }\n',
      id: 'net.http_client',
    );
    plantsText(
      'net.socket',
      path: 'lib/core/log/local_log.dart',
      body: 'void f() { Socket.connect(h, p); }\n',
      id: 'net.socket',
    );
    plantsText(
      'net.socket also covers SecureSocket, by substring and on purpose',
      path: 'lib/core/log/local_log.dart',
      body: 'void f() { SecureSocket.connect(h, p); }\n',
      id: 'net.socket',
    );
    plantsText(
      'net.web_socket — dart:io WebSocket arrives on an import every file may make',
      path: 'lib/data/notification_scheduler.dart',
      body: "void f() { WebSocket.userAgent = 'x'; }\n",
      id: 'net.web_socket',
    );

    test('WebSocket.connect( trips BOTH net rows, and that is correct', () {
      // `WebSocket.connect(` contains `Socket.connect(`, so the two substring
      // rows overlap on the one spelling that matters most. Recorded rather
      // than narrowed: a socket call site reported twice is a socket call site
      // reported, and narrowing either row to stop the overlap would cost the
      // SecureSocket and RawSocket coverage that the same substring buys.
      final List<String> violations = gateOn(<String, String>{
        'lib/data/notification_scheduler.dart': 'void f() { WebSocket.connect(u); }\n',
      });
      expect(violations, hasLength(2));
      expect(violations.map((String v) => v.split(']').first), <String>[
        '[net.socket',
        '[net.web_socket',
      ]);
    });
    plantsText(
      'net.image_network',
      path: 'lib/core/ui/components/shed_photo.dart',
      body: 'Widget b() => Image.network(u);\n',
      id: 'net.image_network',
    );
    plantsText(
      'net.pdf_fonts fires on the identifier, before the import is even added',
      path: 'lib/features/export/pdf_builder.dart',
      body: 'final f = PdfGoogleFonts.helvetica();\n',
      id: 'net.pdf_fonts',
    );
    plantsText(
      'net.sync_timer — no exemption, because the one ticker uses Future.delayed',
      path: 'lib/core/time/ticker.dart',
      body: 'void f() { Timer.periodic(d, cb); }\n',
      id: 'net.sync_timer',
    );

    test('every _bannedEverywhere entry fires, and names its URI', () {
      for (final String uri in bannedPackageUris) {
        final List<String> violations = gateOn(<String, String>{
          'lib/data/export_repository.dart': "import '$uri';\n",
        });
        // At least one, not exactly one: `package:google_fonts/…` also trips
        // type.google_fonts, which matches the identifier as well as the URI.
        // Two rows firing on one line is two documents agreeing, not a defect.
        expect(
          violations.where((String v) => v.contains('[layer.import]')),
          hasLength(1),
          reason: '$uri: ${violations.join("\n")}',
        );
        expect(violations.first, contains(uri));
      }
    });

    test('dart:io itself is legal — the claim is about sockets, not the filesystem', () {
      expect(
        gateOn(<String, String>{
          'lib/data/media_store.dart': "import 'dart:io';\nFile f(String p) => File(p);\n",
        }),
        isEmpty,
      );
    });

    test("the ticker's real shape needs no exemption", () {
      expect(
        gateOn(<String, String>{
          'lib/core/time/ticker.dart': 'Future<void> f() => Future.delayed(d);\n',
        }),
        isEmpty,
      );
    });

    test('test/ is scanned for the package half', () {
      final List<String> violations = gateOn(<String, String>{
        'test/support/fake_share_service.dart': "import 'package:dio/dio.dart';\n",
      });
      expect(violations, hasLength(1));
      expect(violations.single, contains('[layer.import]'));
    });

    test('test/ is not scanned for the lib/-scoped rows', () {
      // Widening a row's scope is a CONVENTIONS §6 ruling, not a keyboard
      // decision, so the current scope is asserted rather than assumed.
      expect(
        gateOn(<String, String>{'test/support/harness.dart': 'Widget b() => Image.network(u);\n'}),
        isEmpty,
      );
    });
  });

  group('G2 — the direct-dependency allowlist over pubspec.lock', () {
    String lockWith(String name, String kind) =>
        '# Generated by pub\n'
        'packages:\n'
        '  $name:\n'
        '    dependency: "$kind"\n'
        '    description:\n'
        '      name: $name\n'
        '    source: hosted\n'
        '    version: "1.0.0"\n'
        'sdks:\n'
        '  dart: ">=3.12.0 <4.0.0"\n';

    test('G2 exits 1 on a package added to pubspec.lock dependencies but not the allowlist', () {
      final List<String> violations = gateOn(
        const <String, String>{},
        lockfile: lockWith('connectivity_plus', 'direct main'),
      );
      expect(violations, hasLength(1), reason: violations.join('\n'));
      expect(violations.single, contains('[dep.direct_main]'));
      expect(violations.single, contains('connectivity_plus'));
      expect(
        violations.single,
        contains('direct main'),
        reason: 'the message must name the section, or the reader edits the wrong one',
      );
    });

    test('the same package as direct dev is a different section and a different id', () {
      // Not one list read three times: build_runner legitimately drags shelf and
      // web_socket_channel into the graph as dev-only.
      final List<String> violations = gateOn(
        const <String, String>{},
        lockfile: lockWith('connectivity_plus', 'direct dev'),
      );
      expect(violations.single, contains('[dep.direct_dev]'));
    });

    test('a transitive package gets the transitive id and section', () {
      final List<String> violations = gateOn(
        const <String, String>{},
        lockfile: lockWith('connectivity_plus', 'transitive'),
      );
      expect(violations.single, contains('[dep.transitive]'));
    });

    test('an allowlisted package in the WRONG section is still reported', () {
      // Putting in_app_purchase_android under [dependencies] instead of
      // [transitive] gives a red gate whose message reads like the package is
      // unknown when the real fault is the section. Asserted so the message is
      // at least right about which section it looked in.
      final List<String> violations = gateOn(
        const <String, String>{},
        allowlist: '[dependencies]\nzeta\n[dev_dependencies]\n[transitive]\n[exempt]\n',
        lockfile: lockWith('zeta', 'transitive'),
      );
      expect(violations.single, contains('[dep.transitive]'));
    });

    test('a missing pubspec.lock is exit 2, not exit 0', () {
      final Directory temp = _tree(const <String, String>{}, allowlist: _emptyAllowlist);
      addTearDown(() => temp.deleteSync(recursive: true));
      expect(
        () => runPolicy(root: temp.path),
        throwsA(
          isA<PolicyConfigProblem>().having(
            (PolicyConfigProblem p) => p.message,
            'message',
            contains('pubspec.lock'),
          ),
        ),
        reason: 'it means flutter pub get has not run; a clean report would be a lie',
      );
    });

    test('the sdks: block is skipped, and dart is never reported as a package', () {
      expect(gateOn(const <String, String>{}), isEmpty);
      expect(lockfileKinds('.').keys, isNot(contains('dart')));
    });

    test('the parser finds the real lockfile, not zero packages', () {
      // The two anchors are exact — two spaces and a line that ENDS at the
      // colon, four spaces for the kind. A lockfile written with different
      // indentation would match nothing and G2 would pass on everything.
      final Map<String, String> kinds = lockfileKinds('.');
      expect(
        kinds.length,
        greaterThan(100),
        reason:
            'parsed ${kinds.length} packages from the real pubspec.lock — the anchors have moved',
      );
      expect(
        kinds.values.toSet(),
        containsAll(<String>['direct main', 'direct dev', 'transitive']),
      );
    });

    test(
      "decision #5's four in_app_purchase packages are allowlisted, three of them transitive",
      () {
        final Map<String, Set<String>> allow = readAllowlist('.');
        expect(allow['dependencies'], contains('in_app_purchase'));
        expect(
          allow['transitive'],
          containsAll(<String>[
            'in_app_purchase_android',
            'in_app_purchase_storekit',
            'in_app_purchase_platform_interface',
          ]),
        );
      },
    );

    test('http is on the transitive allowlist and nothing bans it in the lockfile', () {
      // Four regular edges, measured 2026-08-01: timezone, package_info_plus,
      // file_selector_platform_interface and image_picker_platform_interface.
      // A rule that banned it would mean deleting reminders, the wakelock, the
      // file picker and the photo picker.
      expect(readAllowlist('.')['transitive'], contains('http'));
      expect(lockfileKinds('.')['http'], 'transitive');
    });
  });

  group('the design rules — 06 §3.5, CONVENTIONS §4.7', () {
    /// Rule id → the smallest source that must trip it.
    ///
    /// Data, not thirty hand-written `test()` bodies: that is where a row lands
    /// with no case and N03-T07's inventory goes red two tasks later for a
    /// reason nobody can find. The count is never written down as a number —
    /// derive it from the table, because three documents already disagree about
    /// how many `gesture.*` rows there are (CODE-REVIEW-CHECKLIST §1.8: count
    /// the table, never the sentence).
    const Map<String, String> trips = <String, String>{
      'token.raw_color': 'const c = Color(0xFF0B0D0E);',
      'token.material_color': 'const c = Colors.transparent;',
      'token.raw_color_ctor': 'const c = Color.fromARGB(255, 1, 2, 3);',
      'token.seeded_scheme': 'final s = ColorScheme.fromSeed(seedColor: c);',
      'token.literal_font_size': 'const t = TextStyle(fontSize: 20);',
      'token.primitives_import': "import 'package:shed_book/core/ui/primitives.dart';",
      'token.magic_size': 'Widget b() => SizedBox(height: 12);',
      'theme.mode': 'final m = ThemeMode.system;',
      'theme.brightness': 'final b = Brightness.light;',
      'theme.platform_brightness': 'final b = MediaQuery.platformBrightnessOf(context);',
      'theme.light_factory': 'final s = ColorScheme.light();',
      'type.google_fonts': 'final f = GoogleFonts.inter();',
      'type.clamp': 'Widget b() => MediaQuery.withClampedTextScaling(child: c);',
      'type.weight_cap': 'const w = FontWeight.w800;',
      'type.fitted_box': 'Widget b() => FittedBox(child: c);',
      'gesture.dismissible': 'Widget b() => Dismissible(key: k, child: c);',
      'gesture.draggable': 'Widget b() => Draggable(child: c, feedback: f);',
      'gesture.tooltip': 'Widget b() => Tooltip(message: m, child: c);',
      'gesture.long_press_draggable': 'Widget b() => LongPressDraggable(child: c, feedback: f);',
      'gesture.interactive_viewer': 'Widget b() => InteractiveViewer(child: c);',
      'gesture.refresh': 'Widget b() => RefreshIndicator(child: c, onRefresh: r);',
      'gesture.long_press': 'Widget b() => GestureDetector(onLongPress: f);',
      'gesture.scale': 'Widget b() => GestureDetector(onScaleStart: f);',
      'gesture.drag': 'Widget b() => GestureDetector(onHorizontalDragStart: f);',
      'gesture.drag_handle': 'void f() => showModalBottomSheet(showDragHandle: true);',
      'gesture.sheet_drag': 'void f() => showModalBottomSheet(enableDrag: true);',
      'gesture.slider': 'Widget b() => Slider(value: v, onChanged: c);',
      'gesture.horizontal_swipe': 'Widget b() => PageView(children: c);',
      'gesture.raw_snackbar': 'void f() { m.showSnackBar(s); }',
      'a11y.scale_factor': 'final s = MediaQuery.of(context).textScaleFactor;',
      'a11y.header_bool': 'Widget b() => Semantics(header: true, child: c);',
      'a11y.announce': 'void f() => SemanticsService.announce(m, d);',
      'a11y.sort_key': 'Widget b() => Semantics(sortKey: const OrdinalSortKey(1), child: c);',
      'a11y.merge_semantics': 'Widget b() => MergeSemantics(child: c);',
      'a11y.material_picker': 'void f() => showDatePicker(context: c);',
      'ui.show_dialog': 'void f() => showDialog(context: c, builder: b);',
    };

    /// The rows scoped narrower than `lib/`, each needing its own path.
    const Map<String, String> scopedPath = <String, String>{
      'token.color_scheme_read': 'lib/features/flock/flock_screen.dart',
      'token.color_scheme_read_ui': 'lib/core/ui/components/shed_pen_tile.dart',
      'theme.deprecated_scheme_role': 'lib/core/ui/theme.dart',
      'ui.spinner': 'lib/features/flock/flock_screen.dart',
      // **SCOPED TO THE 3AM SCREEN, WHICH IS THE WHOLE RULE.** #90: nothing
      // monetization-related renders there at any entitlement state — and a
      // screen that merely WATCHES the entitlement is the shape that ships,
      // because it renders nothing today and flashes a paywall on the first slow
      // frame after somebody adds a row to it.
      'ui.monetization_surface': 'lib/features/quick_entry/quick_entry_screen.dart',
    };

    /// The body each narrowly-scoped row needs, since they do not share one.
    const Map<String, String> scopedBody = <String, String>{
      'token.color_scheme_read': 'final c = Theme.of(context).colorScheme;',
      'token.color_scheme_read_ui': 'final c = Theme.of(context).colorScheme;',
      'theme.deprecated_scheme_role': 'const s = ColorScheme(background: c);',
      'ui.spinner': 'Widget b() => CircularProgressIndicator();',
      'ui.monetization_surface': 'final u = ref.watch(entitlementProvider);',
    };

    test('design.raw_hex, design.magic_size, design.banned_gesture, design.snackbar, '
        'design.spinner and design.dialog each exit 1 on their planted violation', () {
      // The anchor. The six names are the plan's shorthand; the ids are
      // CONVENTIONS §4.7's, because there is no `design` namespace.
      const Map<String, String> six = <String, String>{
        'token.raw_color': 'const c = Color(0xFF0B0D0E);',
        'token.magic_size': 'Widget b() => SizedBox(height: 12);',
        'gesture.dismissible': 'Widget b() => Dismissible(key: k, child: c);',
        'gesture.raw_snackbar': 'void f() { m.showSnackBar(s); }',
        'ui.show_dialog': 'void f() => showDialog(context: c, builder: b);',
      };
      six.forEach((String id, String body) {
        final List<String> violations = gateOn(<String, String>{
          'lib/features/lambing/lambing_screen.dart': '$body\n',
        });
        expect(violations.map((String v) => v.split(']').first.substring(1)), contains(id));
      });
      // ui.spinner is scoped lib/features/ and gets its own planting.
      expect(
        gateOn(<String, String>{
          'lib/features/flock/flock_screen.dart': 'Widget b() => CircularProgressIndicator();\n',
        }).single,
        contains('[ui.spinner]'),
      );
    });

    test('every design row fires on its own planted violation', () {
      for (final MapEntry<String, String> entry in trips.entries) {
        final List<String> violations = gateOn(<String, String>{
          'lib/features/lambing/lambing_screen.dart': '${entry.value}\n',
        });
        expect(
          violations.map((String v) => v.split(']').first.substring(1)),
          contains(entry.key),
          reason: '${entry.key} did not fire on: ${entry.value}',
        );
      }
      for (final MapEntry<String, String> entry in scopedPath.entries) {
        final List<String> violations = gateOn(<String, String>{
          entry.value: '${scopedBody[entry.key]}\n',
        });
        expect(
          violations.map((String v) => v.split(']').first.substring(1)),
          contains(entry.key),
          reason: '${entry.key} did not fire under ${entry.value}',
        );
      }
    });

    test('every rule id in the two text tables has a case in this file', () {
      // The half of N03-T07's inventory this task can already hold: nothing in
      // the design tables may exist without a planting above.
      final Set<String> covered = <String>{...trips.keys, ...scopedPath.keys};
      final Set<String> design = policyRuleIds
          .where(
            (String id) => <String>[
              'token.',
              'theme.',
              'type.',
              'gesture.',
              'a11y.',
              'ui.',
            ].any(id.startsWith),
          )
          // type.error_name shares the `type.` namespace and is a vocabulary
          // row, not a design one — CONVENTIONS §4.7 gives namespaces, not
          // ownership. Its case is in the vocabulary group.
          .where((String id) => id != 'type.error_name')
          .toSet();
      expect(design.difference(covered), isEmpty, reason: 'design rows with no planting case');
      expect(
        covered.difference(design),
        isEmpty,
        reason: 'planting cases for rows that do not exist',
      );
    });

    void allowsBody(String title, String path, String body) {
      test(title, () => expect(gateOn(<String, String>{path: '$body\n'}), isEmpty));
    }

    const String pens = 'lib/features/pens/pen_board_screen.dart';
    allowsBody(
      'EdgeInsets.all(0) — 0 is not magic',
      pens,
      'Widget b() => Padding(padding: EdgeInsets.all(0));',
    );
    allowsBody('SizedBox(height: 1) — 1 is not magic', pens, 'Widget b() => SizedBox(height: 1);');
    allowsBody('SizedBox(height: 1.0) — nor is 1.0', pens, 'Widget b() => SizedBox(height: 1.0);');
    allowsBody(
      'SizedBox(height: kGap) — a named constant is the remedy the rule asks for',
      pens,
      'Widget b() => SizedBox(height: kGap);',
    );
    allowsBody(
      'enableDrag: false is the sheet the app actually builds',
      pens,
      'void f() => s(enableDrag: false);',
    );

    test(
      'SizedBox(height: 1.5) is one violation — a hairline that is not a token is still magic',
      () {
        final List<String> violations = gateOn(<String, String>{
          pens: 'Widget b() => SizedBox(height: 1.5);\n',
        });
        expect(violations, hasLength(1));
        expect(violations.single, contains('[token.magic_size]'));
      },
    );

    test('both announce spellings fire, and the second is the one 06 §3.5 would have missed', () {
      final List<String> violations = gateOn(<String, String>{
        'lib/features/pens/a.dart': 'void f() => SemanticsService.announce(m, d);\n',
        'lib/features/pens/b.dart': 'void f() => SemanticsService.sendAnnouncement(m, d);\n',
      });
      expect(violations, hasLength(2));
      expect(violations.every((String v) => v.contains('[a11y.announce]')), isTrue);
    });

    test('feedback.dart has NO exemption for showSnackBar — this is P2', () {
      // The case a future contributor will try to delete, in good faith, after
      // reading CONVENTIONS §2.11 or R30. Both are superseded.
      final List<String> violations = gateOn(<String, String>{
        'lib/core/ui/feedback.dart': 'void f() { m.showSnackBar(s); }\n',
      });
      expect(violations, hasLength(1));
      expect(violations.single, contains('[gesture.raw_snackbar]'));
    });

    group('the R56 exemptions, live for the first time', () {
      const String r56 = '''
[dependencies]
[dev_dependencies]
[transitive]
[exempt]
lib/core/time/app_clock.dart       :: time.dart_clock
lib/core/ui/night_error_panel.dart :: token.raw_color
lib/core/ui/primitives.dart        :: token.raw_color
lib/core/ui/palettes.dart          :: token.primitives_import
''';

      test('primitives.dart may hold a raw hex', () {
        expect(
          gateOn(<String, String>{
            'lib/core/ui/primitives.dart': 'const c = Color(0xFF0B0D0E);\n',
          }, allowlist: r56),
          isEmpty,
        );
      });

      test('palettes.dart may import primitives', () {
        expect(
          gateOn(<String, String>{
            'lib/core/ui/palettes.dart': "import 'package:shed_book/core/ui/primitives.dart';\n",
          }, allowlist: r56),
          isEmpty,
        );
      });

      test('a third file importing primitives is not exempt — the waiver names one path', () {
        final List<String> violations = gateOn(<String, String>{
          'lib/core/ui/components/shed_pen_tile.dart':
              "import 'package:shed_book/core/ui/primitives.dart';\n",
        }, allowlist: r56);
        expect(violations.single, contains('[token.primitives_import]'));
      });
    });

    test('a raw hex in a generated file is never scanned', () {
      expect(
        gateOn(<String, String>{'lib/core/db/database.g.dart': 'const c = Color(0xFF0B0D0E);\n'}),
        isEmpty,
      );
    });
  });

  group('the time, db, rp3 and vocabulary rules', () {
    // Every snippet for a row scoped to BOTH roots is assembled from halves, so
    // this file — which lives under a scanned root — never contains the literal
    // whole. That is one of the two ways out the epic names; the other is a
    // fifth [exempt] line, and there is no fifth [exempt] line.
    final String nowCall =
        'DateTime'
        '.now(';

    // The anchor's own TITLE contains the literal `time.dart_clock` bans, and
    // that rule reaches `test/`. Split across adjacent string literals: Dart
    // concatenates them with no separator, so the test's NAME is the backlog's
    // anchor verbatim while this file's source text never holds the needle whole.
    test('time.wall_clock exits 1 on a second DateTime'
        '.now( call site '
        'and copy.banned_word exits 1 on the word dr'
        'aft', () {
      // The exemption is proved by the file that does NOT appear.
      final List<String> violations = gateOn(
        <String, String>{
          'lib/core/time/app_clock.dart': 'final t = $nowCall);\n',
          'lib/data/lambing_repository.dart': 'final t = $nowCall);\n',
        },
        allowlist:
            '$_emptyAllowlist'
            'lib/core/time/app_clock.dart :: time.dart_clock\n',
      );
      expect(violations, hasLength(1), reason: violations.join('\n'));
      expect(violations.single, contains('[time.dart_clock]'));
      expect(violations.single, contains('lib/data/lambing_repository.dart'));

      final List<String> word = gateOn(<String, String>{
        'lib/features/lambing/lambing_screen.dart':
            'const s = '
            "'dr"
            "aft';\n",
      });
      expect(word, hasLength(1));
      expect(word.single, contains('[copy.banned_word]'));
    });

    test('the five SQL-side time spellings each fire under their own id', () {
      const Map<String, String> sql = <String, String>{
        'time.sql_now_1': "const q = \"date('now')\";",
        'time.sql_now_2': "const q = \"datetime('now')\";",
        'time.sql_now_3': "const q = 'CURRENT_TIMESTAMP';",
        'time.sql_now_4': "const q = 'CURRENT_DATE';",
        'time.sql_now_5': "const q = 'CURRENT_TIME';",
      };
      sql.forEach((String id, String body) {
        final List<String> violations = gateOn(<String, String>{
          'lib/core/db/queries.dart': '$body\n',
        });
        expect(violations.map((String v) => v.split(']').first.substring(1)), contains(id));
      });
    });

    test('time.dart_clock reaches the test tier — a test that reads the real clock '
        'depends on the day it runs', () {
      final List<String> violations = gateOn(<String, String>{
        'test/data/lambing_repository_test.dart': 'final t = $nowCall);\n',
      });
      expect(violations, hasLength(1));
      expect(violations.single, contains('[time.dart_clock]'));
    });

    test('db.raw_statement fires under lib/data/ and not at the legal site', () {
      expect(
        gateOn(<String, String>{
          'lib/data/pen_repository.dart': 'void f() => customStatement(sql);\n',
        }).single,
        contains('[db.raw_statement]'),
      );
      expect(
        gateOn(<String, String>{
          'lib/core/db/connection.dart': 'void f() => customStatement(sql);\n',
          'lib/core/db/queries.drift.dart': 'void f() => customStatement(sql);\n',
        }),
        isEmpty,
        reason: 'lib/core/db/ is the single writer; the .drift.dart file is generated',
      );
    });

    test('db.save_verb — there is no save(aggregate) anywhere', () {
      expect(
        gateOn(<String, String>{
          'lib/data/flock_repository.dart': 'Future<void> saveEwe(Ewe e) async {}\n',
        }).single,
        contains('[db.save_verb]'),
      );
    });

    test('every rp3 row fires on the 3.x spelling it bans', () {
      // Fragments again: eleven of the thirteen are scoped to both roots.
      final Map<String, String> rp3 = <String, String>{
        'rp3.retry':
            'ProviderScope(re'
            'try: r);',
        'rp3.container_test':
            'final c = ProviderContainer'
            '.test();',
        'rp3.is_auto_dispose':
            'final b = p.is'
            'AutoDispose;',
        'rp3.mutation':
            'final m = Muta'
            'tion<int>();',
        'rp3.value_or_null':
            'final v = a.value'
            'OrNull;',
        'rp3.ref_mounted':
            'if (ref.mou'
            'nted) {}',
        'rp3.observer_context':
            'void f(ProviderObserver'
            'Context c) {}',
        'rp3.state_provider':
            'final p = State'
            'Provider((r) => 0);',
        'rp3.state_notifier':
            'class C extends State'
            'Notifier<int> {}',
        'rp3.annotation':
            "import 'package:riverpod"
            "_annotation/x.dart';",
        'rp3.hooks':
            "import 'package:hooks"
            "_riverpod/x.dart';",
      };
      rp3.forEach((String id, String body) {
        final List<String> violations = gateOn(<String, String>{
          'lib/features/flock/flock_controller.dart': '$body\n',
        });
        expect(
          violations.map((String v) => v.split(']').first.substring(1)),
          contains(id),
          reason: '$id did not fire on: $body',
        );
      });
    });

    test('rp3.tester_container is test/ only and rp3.overrides is lib/ only', () {
      final String testerContainer =
          'tester'
          '.container';
      expect(
        gateOn(<String, String>{
          'test/features/flock_screen_test.dart': 'final c = $testerContainer;\n',
        }).single,
        contains('[rp3.tester_container]'),
      );
      // The harness at N12 is built entirely out of overrideWith. A row scoped
      // to both roots would make it unwritable.
      expect(
        gateOn(<String, String>{
          'test/support/harness.dart': 'final o = dbProvider.overrideWith((r) => fake);\n',
        }),
        isEmpty,
      );
      expect(
        gateOn(<String, String>{
          'lib/app.dart': 'final o = dbProvider.overrideWith((r) => fake);\n',
        }).single,
        contains('[rp3.overrides]'),
      );
    });

    test('stream and stat rows fire, and stat is scoped to the two statistic surfaces', () {
      expect(
        gateOn(<String, String>{
          'lib/data/season_repository.dart': 'final s = combineLatest(a, b);\n',
        }).single,
        contains('[stream.combine]'),
      );
      expect(
        gateOn(<String, String>{
          'lib/features/season/season_controller.dart': 'void f() => ref.invalidate(p);\n',
        }).map((String v) => v.split(']').first.substring(1)),
        contains('stream.invalidate'),
      );

      // THE NARROWING, DRILLED FROM BOTH SIDES (2026-08-02). The rule moved from
      // the substring family to the pattern family with a negative lookahead for
      // the two architected arguments — 02 §4.1's ticker on resume and 04 §7
      // step 14's database reopen. Neither has a drift stream behind it, which
      // is exactly what the ban is scoped to.
      //
      // The `[exempt]` line CODE-REVIEW-CHECKLIST §1.5 offered as the other move
      // would have deleted the rule for one whole file and would not have
      // reached the restore flow at all. These four assertions are what make the
      // narrower move safe: it still fires on everything else, in the same two
      // files.
      for (final String allowed in <String>['minuteTickProvider', 'databaseProvider']) {
        expect(
          gateOn(<String, String>{'lib/app.dart': 'void f() => ref.invalidate($allowed);\n'}),
          isEmpty,
          reason: '$allowed is architected',
        );
      }
      expect(
        gateOn(<String, String>{
          'lib/app.dart': 'void f() => ref.invalidate(settingsProvider);\n',
        }).map((String v) => v.split(']').first.substring(1)),
        contains('stream.invalidate'),
        reason: 'the allowance is two arguments, not one file',
      );
      expect(
        gateOn(<String, String>{
          'lib/app.dart': 'void f() => ref.invalidate(minuteTickProviderish);\n',
        }).map((String v) => v.split(']').first.substring(1)),
        contains('stream.invalidate'),
        reason: 'the lookahead closes on the paren, so a longer name is not the allowance',
      );
      expect(
        gateOn(<String, String>{
          'lib/features/season/season_controller.dart': 'final n = count ?? 0;\n',
        }).single,
        contains('[stat.zero_default]'),
      );
      expect(
        gateOn(<String, String>{
          'lib/features/pens/pen_board_controller.dart': 'final n = count ?? 0;\n',
        }),
        isEmpty,
        reason: 'only the season and flock statistic surfaces are scoped',
      );
    });

    group('the false positives that decide the vocabulary rule’s shape', () {
      test('existsSync, readAsStringSync and listSync are not a banned word', () {
        // If this case is red the rule is substring-matching `sync` and will be
        // deleted by whoever meets it — which is how the real rules go too.
        expect(
          gateOn(<String, String>{
            'lib/data/media_store.dart':
                'final a = f.existsSync();\n'
                'final b = f.readAsStringSync();\n'
                'final c = d.listSync();\n',
          }),
          isEmpty,
        );
      });

      test('the sync* generator keyword is not a banned word', () {
        expect(
          gateOn(<String, String>{
            'lib/domain/stats/losses.dart': 'Iterable<int> f() sync* { yield 1; }\n',
          }),
          isEmpty,
        );
      });

      test('framework error types are legal; a declared *Error class is not', () {
        expect(
          gateOn(<String, String>{
            'lib/main.dart':
                'void f() { throw StateError(m); }\n'
                'void g() { FlutterError.onError = h; }\n'
                'void i() { throw ArgumentError(m); }\n',
          }),
          isEmpty,
        );
        expect(
          gateOn(<String, String>{
            'lib/domain/validation/x.dart': 'class LambingError implements Exception {}\n',
          }).single,
          contains('[type.error_name]'),
        );
      });

      test('pendingRequests is legal; the bare word is not', () {
        expect(
          gateOn(<String, String>{'lib/data/x.dart': 'final n = pendingRequests;\n'}),
          isEmpty,
        );
        expect(
          gateOn(<String, String>{
            'lib/data/x.dart':
                'const s = '
                "'pend"
                "ing';\n",
          }).single,
          contains('[copy.banned_word]'),
        );
      });
    });

    group('the ARB reader — 10 §10(a)', () {
      String arb(String key, String value, {String? description}) =>
          '{\n'
          '  "$key": "$value",\n'
          '  "@$key": {\n'
          '    "description": "${description ?? 'a description'}"\n'
          '  }\n'
          '}\n';

      test('a banned word in a message value is a violation, naming the key', () {
        final List<String> violations = gateOn(<String, String>{
          'lib/l10n/app_en.arb': arb(
            'quickEntryTitle',
            'Your dr'
                'aft is here',
          ),
        });
        expect(violations, hasLength(1));
        expect(violations.single, contains('[copy.banned_word]'));
        expect(violations.single, contains('quickEntryTitle'));
      });

      test('the same word in a description is not', () {
        // 10 §8 requires a description on every string, and the description of a
        // message about one has to be able to say so.
        expect(
          gateOn(<String, String>{
            'lib/l10n/app_en.arb': arb(
              'quickEntryTitle',
              'Quick Entry',
              description:
                  'Never says dr'
                  'aft, because there is none',
            ),
          }),
          isEmpty,
        );
      });

      test('the FULL word list runs over the ARB, sync included', () {
        // `existsSync` cannot appear in an ARB message, so the word that is
        // unusable over Dart is usable here.
        final List<String> violations = gateOn(<String, String>{
          'lib/l10n/app_en.arb': arb(
            'settingsBody',
            'Nothing to sy'
                'nc',
          ),
        });
        expect(violations.single, contains('[copy.banned_word]'));
      });

      test('a tier-3 claim in the ARB is its own violation', () {
        final List<String> violations = gateOn(<String, String>{
          'lib/l10n/app_en.arb': arb(
            'aboutOffline',
            'your data never leaves '
                'your phone',
          ),
        });
        expect(
          violations.map((String v) => v.split(']').first.substring(1)),
          contains('copy.tier3_claim'),
        );
      });

      test('the real ARB is clean', () {
        expect(runPolicy().where((String v) => v.contains('app_en.arb')), isEmpty);
      });
    });

    test('copy.tier3_claim fires under lib/, and the permitted wording does not', () {
      final List<String> violations = gateOn(<String, String>{
        'lib/features/settings/about_screen.dart':
            "const s = 'your data never leaves "
            "your phone';\n",
      });
      expect(
        violations.map((String v) => v.split(']').first.substring(1)),
        contains('copy.tier3_claim'),
      );
      expect(
        gateOn(<String, String>{
          'lib/features/settings/about_screen.dart':
              "const s = 'Shed Book has no account, no server and no s"
              "ync.';\n",
        }),
        isEmpty,
        reason: "decision-record §3.1's own paragraph must pass the rule that protects it",
      );
    });

    test('the vocabulary rules read declarations; the API rules read every line', () {
      // Added 2026-08-01 after grams.dart's "provisional pending open question
      // 12" tripped copy.banned_word on the ordinary English word. The line is
      // between two kinds of rule: a commented-out banned CALL is one keystroke
      // from being real, and a comment saying "there is no draft state" is the
      // sentence that keeps the rule alive.
      expect(
        gateOn(<String, String>{
          'lib/data/flock_repository.dart':
              '// There is no dr'
              'aft state and no s'
              'ave(aggregate) here.\n'
              '// A failure type is never called an Err'
              'or.\n'
              'void beginLambing() {}\n',
        }),
        isEmpty,
      );
      // The same words in code still fire.
      expect(
        gateOn(<String, String>{
          'lib/data/flock_repository.dart':
              'const s = '
              "'dr"
              "aft';\n",
        }).single,
        contains('[copy.banned_word]'),
      );
      // And an API rule is unaffected by the comment marker: a commented-out
      // gesture is one keystroke from being real.
      expect(
        gateOn(<String, String>{
          'lib/features/lambing/lambing_screen.dart':
              '// Widget b() => Dismissible(key: k, child: c);\n',
        }).single,
        contains('[gesture.dismissible]'),
      );
    });

    test('the two copy.* CONTENT rules arrived with N06-T09', () {
      // Inverted from "deliberately absent" in the commit that landed them, and
      // kept rather than deleted: the pair is what stops either rule being
      // removed in a tidy-up with a green suite.
      expect(policyRuleIds, contains('copy.vet_advice'));
      expect(policyRuleIds, contains('copy.disclaimer_retyped'));
    });
  });

  group('the inventory — every rule is proved', () {
    test('every rule id in the table is proved by a test in this file', () {
      final Set<String> ids = policyRuleIds.toSet();
      final Set<String> proved = firesOn.keys.toSet();
      expect(
        ids.difference(proved),
        isEmpty,
        reason:
            'rule ids in the table with no proving case — a rule nobody has seen fire is '
            'indistinguishable from a broken rule',
      );
      // The reverse, and it is the line that catches a deletion: a proving case
      // for an id that is no longer in the table passes for ever and proves
      // nothing, which is how a rule is removed in a tidy-up with a green suite.
      expect(
        proved.difference(ids),
        isEmpty,
        reason: 'proving cases for rule ids the table no longer carries',
      );
      expect(ids, isNotEmpty, reason: 'an empty table would satisfy both differences');
    });

    test('every planted violation actually fires under its own id', () {
      firesOn.forEach((String id, Planted planted) {
        final List<String> violations = gateOn(<String, String>{
          planted.path: '${planted.source}\n',
          ...?planted.extra,
        }, lockfile: planted.lockfile ?? _emptyLockfile);
        expect(
          violations.map((String v) => v.split(']').first.substring(1)),
          contains(id),
          reason: '$id did not fire on ${planted.path}: ${planted.source}',
        );
      });
    });

    test('every id matches CONVENTIONS §4.7 — a namespace and a lower_snake tail', () {
      // Three task titles in this very epic use ids that violate it —
      // design.raw_hex, time.wall_clock, db.custom_statement. Without this
      // assertion the fourth one lands and the [exempt] key that references it
      // never matches, silently, for ever.
      final RegExp grammar = RegExp(
        r'^(layer|net|time|rp3|stream|db|stat|a11y|gesture|token|theme|type|ui|main|dep|launch|copy|media|export|share)'
        r'\.[a-z0-9_]+$',
      );
      for (final String id in policyRuleIds) {
        expect(grammar.hasMatch(id), isTrue, reason: '$id is not a CONVENTIONS §4.7 rule id');
      }
    });

    test('no id appears twice — R54, a duplicate rule is weakened twice', () {
      final List<String> ids = policyRuleIds.toList();
      expect(ids.toSet(), hasLength(ids.length), reason: ids.join(', '));
    });

    test('the ids that no table row carries are still yielded', () {
      // dep.* is built by string interpolation inside _checkLockfile and
      // layer.import comes from _bannedEverywhere. Neither appears in a table,
      // and an id the getter cannot see is a rule the inventory cannot police.
      expect(
        policyRuleIds,
        containsAll(<String>[
          'dep.direct_main',
          'dep.direct_dev',
          'dep.transitive',
          'layer.import',
        ]),
      );
      // 01 §3.2's two generic ids are replaced, not supplemented.
      expect(policyRuleIds, isNot(contains('layer.direction')));
    });

    test('the remaining deliberate absences are still absent, and the source says why', () {
      // copy.vet_advice and copy.disclaimer_retyped left this list at N06-T09.
      // What is still absent is named by the header comment, with the task that
      // brings each one.
      expect(policyRuleIds, isNot(contains('db.destructive_ddl')));
      expect(policyRuleIds, isNot(contains('layer.in_app_purchase')));
      final String source = File('tool/check_policy.dart').readAsStringSync();
      expect(source, contains('N08'), reason: 'db.destructive_ddl arrives with the harness');
      expect(source, contains('N30'), reason: 'the monetization rules arrive with N30');
    });
  });

  group('the gate is wired into CI', () {
    final List<String> workflow = File('.github/workflows/ci.yml').readAsLinesSync();

    /// The 0-based index of the first line in the `gate` job containing [needle],
    /// ignoring comment lines — a step is a `run:`, never a `#`.
    int stepAt(String needle) =>
        workflow.indexWhere((String l) => !l.trimLeft().startsWith('#') && l.contains(needle));

    test('ci.yml runs the policy gate before format and analyze', () {
      final int policy = stepAt('tool/check_policy.dart');
      final int format = stepAt('dart format');
      final int analyze = stepAt('flutter analyze');
      final int pubGet = stepAt('flutter pub get');
      expect(policy, isNot(-1), reason: 'the gate job does not run tool/check_policy.dart');
      // 01 §3.3 and 13 §4.3 both put it AFTER pub get, and they are right: a
      // missing lockfile is exit 2, and G2 must read the lockfile CI will build
      // with. It is the first step that can fail on the CONTENTS of the diff.
      expect(policy, greaterThan(pubGet));
      expect(policy, lessThan(format));
      expect(policy, lessThan(analyze));
    });

    test('no step is allowed to fail quietly', () {
      // A gate that cannot fail is not a gate. This is the only way `gate` could
      // have been green for two epics while the script did not exist.
      //
      // Comment lines are filtered, because the workflow's own comment says the
      // key must never appear — the same prohibition-versus-claim distinction
      // that offline_wording_test.dart's marked region exists for.
      expect(
        workflow.where(
          (String l) => !l.trimLeft().startsWith('#') && l.contains('continue-on-error'),
        ),
        isEmpty,
      );
    });

    test('every job needs gate, which is what makes one toolchain assert enough', () {
      final RegExp jobHeader = RegExp(r'^  ([a-z][a-z0-9_-]*):$');
      // From `jobs:` onward only. `on:`'s own two-space children — `push:` and
      // `pull_request:` — match the same shape and are not jobs.
      final int jobsAt = workflow.indexWhere((String l) => l.trimRight() == 'jobs:');
      expect(jobsAt, isNot(-1), reason: 'ci.yml has no jobs: block');
      final List<int> starts = <int>[
        for (int i = jobsAt + 1; i < workflow.length; i++)
          if (jobHeader.hasMatch(workflow[i])) i,
      ];
      expect(starts, isNotEmpty, reason: 'ci.yml declares no jobs');
      final List<String> names = starts
          .map((int i) => jobHeader.firstMatch(workflow[i])!.group(1)!)
          .toList();
      expect(names, contains('gate'));
      for (int j = 0; j < starts.length; j++) {
        if (names[j] == 'gate') {
          continue;
        }
        final int end = j + 1 < starts.length ? starts[j + 1] : workflow.length;
        // Scoped to the job's OWN block: a whole-file `any` would pass on one
        // job's `needs:` while a second job had none.
        expect(
          workflow.sublist(starts[j], end).any((String l) => l.contains('needs: gate')),
          isTrue,
          reason: '${names[j]} does not need gate — 13 §1.1 assumes one assert covers the workflow',
        );
      }
    });

    test('make check runs the gate first', () {
      final List<String> lines = File('Makefile').readAsLinesSync();
      final int start = lines.indexWhere((String l) => l.startsWith('check:'));
      expect(start, isNot(-1));
      final List<String> recipe = lines
          .skip(start + 1)
          .takeWhile((String l) => l.startsWith('\t'))
          .toList();
      expect(recipe.first, contains('tool/check_policy.dart'));
    });
  });

  test('policyRuleIds carries the ten layer rule ids', () {
    // The inventory hook. N03-T07 turns it into an assertion with teeth: every
    // id here has a case in this file.
    expect(
      policyRuleIds,
      containsAll(<String>[
        'layer.domain',
        'layer.core_db',
        'layer.data',
        'layer.data_no_material',
        'layer.features',
        'layer.sibling',
        'layer.core_ui',
        'layer.single_writer',
        'layer.root',
        'layer.data_no_validation',
      ]),
    );
  });

  group('the two copy rules — N06-T09', () {
    // The driver change is the risky half: two table rows alone are a rule that
    // silently passes, because the walk never opened the places these are
    // specified to scan. All three scopes are exercised.

    test('copy.vet_advice fires on a planted dose in a Dart string literal', () {
      expect(
        gateOn(<String, String>{
          'lib/features/lambing/entry.dart': "const String hint = 'Recommended dose is 2 ml/kg.';",
        }),
        contains(startsWith('[copy.vet_advice] lib/features/lambing/entry.dart')),
      );
    });

    test('copy.vet_advice fires on a planted dose in an ARB message value', () {
      expect(
        gateOn(<String, String>{
          // The same shape the ARB-reader group's local helper builds, written
          // out here because that helper is scoped to its own group.
          'lib/l10n/app_en.arb':
              '{\n'
              '  "hint": "You should call the vet.",\n'
              '  "@hint": { "description": "planted" }\n'
              '}\n',
        }),
        contains(startsWith('[copy.vet_advice] lib/l10n/app_en.arb')),
      );
    });

    test('copy.vet_advice fires on a planted dose in assets/content/', () {
      // The scope that needed `assets` added to the walked roots and `.md` added
      // to the scannable extensions. Without both, this rule reports nothing on
      // the one directory whose entire contents are user-facing prose.
      expect(
        gateOn(<String, String>{
          'assets/content/death_cause.md': 'A low birth weight indicates a deficiency.',
        }),
        contains(startsWith('[copy.vet_advice] assets/content/death_cause.md')),
      );
    });

    test('copy.vet_advice does not fire on content_policy.dart itself', () {
      // The file that DECLARES the patterns necessarily contains them. The
      // exception is in the rule, not in [exempt] — R56 fixes the allowlist at
      // four lines and none of them is this.
      expect(
        gateOn(<String, String>{
          'lib/domain/policy/content_policy.dart': "final p = RegExp(r'\\byou should\\b');",
        }).where((String v) => v.startsWith('[copy.vet_advice]')),
        isEmpty,
      );
    });

    test('copy.vet_advice does not fire on ordinary English in a doc comment', () {
      // Measured, not assumed: whole-file scanning fired on seven existing files
      // — "over 100% is normal for this metric", "diagnosis not reached", "the
      // NORMAL state". A standing false positive gets an allowlist, then gets
      // weakened, then gets deleted, while guarding the rule whose regression is
      // the app giving veterinary advice.
      expect(
        gateOn(<String, String>{
          'lib/domain/stats/notes.dart':
              '/// Over 100% is normal for this metric, and a diagnosis is never ours.\n'
              'const int x = 1;\n',
        }).where((String v) => v.startsWith('[copy.vet_advice]')),
        isEmpty,
      );
    });

    test('copy.disclaimer_retyped fires when the footer is typed into a second file', () {
      expect(
        gateOn(<String, String>{
          'lib/features/export/pdf.dart':
              "const String f = 'It is not a statutory medicine record.';",
        }),
        contains(startsWith('[copy.disclaimer_retyped] lib/features/export/pdf.dart')),
      );
    });

    test('copy.disclaimer_retyped fires on a copy split across adjacent literals', () {
      // The gotcha the joiner exists for. Dart wraps long text, so the phrase is
      // never contiguous in the source — which is exactly how a re-typed
      // disclaimer gets formatted.
      expect(
        gateOn(<String, String>{
          'lib/features/export/pdf.dart':
              "const String f = 'It is not a statutory '\n    'medicine record.';",
        }),
        contains(startsWith('[copy.disclaimer_retyped] lib/features/export/pdf.dart')),
      );
    });

    test('copy.disclaimer_retyped does not fire on disclaimers.dart', () {
      expect(
        gateOn(<String, String>{
          'lib/domain/policy/disclaimers.dart':
              "const String f = 'It is not a statutory medicine record.';",
        }).where((String v) => v.startsWith('[copy.disclaimer_retyped]')),
        isEmpty,
      );
    });

    test('the [exempt] allowlist still has exactly five lines', () {
      // R56. Neither new rule bought itself an exemption: both name their one
      // permitted file inside the rule.
      final List<String> exempt = File('tool/policy_allowlist.txt')
          .readAsLinesSync()
          .map((String l) => l.split('#').first.trim())
          .skipWhile((String l) => l != '[exempt]')
          .where((String l) => l.contains('::'))
          .toList();
      // **FIVE SINCE 2026-08-04** (decision-record §7.0d). The fifth is
      // `lib/data/purchase_service.dart :: copy.banned_word` —
      // `PurchaseStatus.pending` is the `in_app_purchase` plugin's own enum member,
      // in the acknowledgement guard and the exhaustive switch arm, and neither is
      // removable or ours.
      //
      // **R56 WAS NEVER ABOUT THE NUMBER FOUR.** It was about a new line requiring
      // somebody to say why, in front of a reader — which is why FOUR SEPARATE
      // TESTS assert this count and all four had to be edited, deliberately, in
      // the commit that added it. The sixth costs the same.
      expect(exempt, hasLength(5));
    });
  });
}
